version: '3.8'

services:
  test:
    container_name: myapp-test
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c 'while ! nc -z myapp-test-mysql 3306; do sleep 1; done && npm run migration:run && npm run test:integration'
    env_file:
      - .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      JWT_PUBLIC_KEY_BASE64: ${JWT_PUBLIC_KEY_BASE64}
      JWT_PRIVATE_KEY_BASE64: ${JWT_PRIVATE_KEY_BASE64}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    networks:
      - myapp-test-network

  mysql:
    container_name: myapp-test-mysql
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - myapp-test-network

networks:
  myapp-test-network:
    driver: bridge
